!IF "$(PLATFORM)" == "x86"
OBJSUFFIX=.obj32
LIBSUFFIX=.lib
DLLSUFFIX=.dll
IDALIB=x86_win_vc_32\ida.lib
IDACXXFLAGS=/D__X86__
GCCLIKECFLAGS=/D__i386
!ELSEIF "$(PLATFORM)" == "x64"
OBJSUFFIX=.obj64
LIBSUFFIX=64.lib
DLLSUFFIX=64.dll
IDALIB=x64_win_vc_64\ida.lib
IDACXXFLAGS=/D__X64__ /D__EA64__
GCCLIKECFLAGS=/D__x86_64
!ELSE
!ERROR Unsupported platform
!ENDIF

CC=cl
CXX=cl
AR=lib
LD=link
LDFLAGS=/DEBUG
RM=del
COMMONCFLAGS=/O2 /Z7 /W3 $(GCCLIKECFLAGS)
COMMONCXXFLAGS=$(COMMONCFLAGS) /EHsc
